/* automatically generated by MySQLtoTS */
import type { n1_param, n2_param, type_param, prop_param } from '#/schemaReduce'

export interface attr_DTYPE {
  desc: string
  type: type_param
  n1: n1_param
  n2: n2_param | 'max'
  len: number
  schema?: prop_param
}

export interface entity_DTYPE {
  [key: string]: attr_DTYPE
  vo?: attr_DTYPE & any
}

export interface testInfo_DTYPE extends entity_DTYPE {
  id: attr_DTYPE
  name: attr_DTYPE
  text: attr_DTYPE
}
