/* automatically generated by MySQLtoTS */
import type { ObjectSchema } from 'fluent-json-schema'
import type { n1_param, n2_param, type_param } from '#/schemaReduce'

export interface attr_DTYPE {
  desc: string
  type: type_param
  n1: n1_param
  n2: n2_param | 'max'
  len: number
  schema?: ObjectSchema
}

export interface entity_DTYPE {
  [key: string]: attr_DTYPE
}

export interface test_info_DTYPE extends entity_DTYPE {
  id: attr_DTYPE // auto_increment
  name: attr_DTYPE
  text: attr_DTYPE
}
