/* automatically generated by MySQLtoTS */
import { n1_param, n2_param, type_param } from '#/schemaReduce'

export interface attr_DTYPE {
  desc: string
  type: type_param
  n1: n1_param
  n2: n2_param | 'max'
  len: number
  schema?: any
}

export interface test_info_DTYPE {
  id: attr_DTYPE // auto_increment
  name: attr_DTYPE
  text: attr_DTYPE
}
